name: Create Changelog

on:
  push:
    branches:
    - 'master'

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT}}


      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.18.0
        with:
          output-file: CHANGELOG.md
          version-file: version.json

